# JDBC URL - aggiungi il prefisso jdbc: davanti alla DATABASE_URL
spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway

# Username e password del database PostgreSQL
spring.datasource.username=postgres
spring.datasource.password=QgPpdsieFbmeJoOLfIqiWqrctABiCOiO

# Driver JDBC PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# HIKARI CONNECTION POOL (FONDAMENTALE)
# ===============================
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000


# JPA / Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server porta (opzionale)
server.port=8080
